Sensors demo in Foxglove
husarion/rosbot-docker pull request #30
Opened 2023-03-21 17:25 UTC by delihus

- Added sensors visualization  for ROSbot in Foxglove
- Updated firmware
![Screenshot from 2023-03-21 17-54-31](https://user-images.githubusercontent.com/109142865/226691446-a094ae70-91db-4388-bb9a-6143d4818867.png)

2023-03-22 15:01 UTC, JanBrzyk reviewed
From my side ok, but @DominikN has to make another review

2023-05-10 13:02 UTC, macstepien requested changes

2023-05-10 13:02 UTC, macstepien commented on Dockerfile.hardware
> +ARG ROSBOT_ROS_RELEASE=0.6.0
I don't think that we should additionally specify rosbot_ros version. We already add version to image tags, when pushing them to dockerhub. That will break current workflow, as after bumping version, rosbot_ros triggers image build, but the old version will be used. Also it will add things to do, when creating new version.

2023-05-10 13:02 UTC, macstepien commented on Dockerfile.simulation
> +ARG ROSBOT_ROS_RELEASE=0.6.0
same here, I'd prefer to just clone most recent version

2023-05-10 13:02 UTC, macstepien commented on README.md
> +| [rosbot-sensors](./demo/) | Visualize all ROSbot sensors |
according to our convention, shouldn't this demo be in the separate `rosbot-sensors` repository?

2023-05-10 13:02 UTC, macstepien commented on demo/config/rosbot_sensors.json
> +{
some other name, e.g. `rosbot_sensors_foxglove.json`, should be more precise

2023-05-12 10:10 UTC, JanBrzyk commented on demo/README.md
> +In the ROSbot's shell execute (in the `/home/husarion/rosbot-docker/demo directory`)
*(in the `/home/husarion/rosbot-docker/demo` directory)

2023-05-12 10:13 UTC, JanBrzyk commented on README.md
Line 8:
Rewrite ROSbots names in the following order:
ROSbot 2R, ROSbot 2 PRO and ROSbot 2.0

2023-05-12 10:16 UTC, JanBrzyk commented on demo/README.md
Add a short info about editing `.env` file

2023-05-12 10:47 UTC, JanBrzyk requested changes
1) Are we planning to add wheel controls to this UI? If it's going to be used in production for hardware testing, it's a must have. And once we have a forward/reverse drive in the demo, it's stupid not to do the rest to make it such a "clickable teleop in the browser". @Jakub Delicat what do you think?

2) graphs for distance sensors still don't work (I updated to husarion/rosbot:humble firmware). After manually adding a topic with a good name and field to the plot, it works normally (as you can see on the screen on ClickUp for the Front Left sensor)

3) I added small cosmetic comments to both README.md in the review

4) The clicked button indicator responds to true/false but the button does not send false when it is unclicked/unclicked, so after one click in Foxglove it stays "Pressed" with a green background forever

5) I would change "Plug charger" to text in two lines, because it does not fit in the specified square (not in one line as it is now)

6) the second time ROSbot respawned outside the blue "grid", but I don't know why and if it's repeatable. After some time it went back to normal

7) The camera and flashing LEDs work great!

2023-05-17 08:07 UTC, delihus commented
@JanBrzyk 
1. I can add component to drive robot with 2 tabs: one for the diff drive teleop, other for the mecanum drive.
2. You have to flash the robot with this version of firmware, from this branch tag `humble-sensors-demo`:
```
docker run \
--rm -it --privileged \
husarion/rosbot:humble-sensors-demo \
/flash-firmware.py /root/firmware.bin
```
3. In progress...
4. Old firmware version look 2.
5. Okay!
6. I will try to reproduce that.
7. Thanks!

2023-05-17 12:44 UTC, delihus commented
Moved to https://github.com/husarion/rosbot-sensors/pull/1

2023-05-17 12:44 UTC, closed without merging