Add simulation and demo
husarion/rosbot-docker pull request #33
Opened 2023-05-17 12:45 UTC by delihus

2023-05-17 12:53 UTC, delihus commented
After build 
https://github.com/husarion/rosbot-docker/actions/runs/5003413773

2023-05-25 10:09 UTC, macstepien requested changes

2023-05-25 10:09 UTC, macstepien commented on Dockerfile.hardware
> +RUN echo $(cat /ros2_ws/src/rosbot_description/package.xml | grep '<version>' | sed -r 's/.*<version>([0-9]+.[0-9]+.[0-9]+)<\/version>/\1/g') >> /version.txt
it will be better to use version from `rosbot` package

2023-05-25 10:09 UTC, macstepien commented on demo/README.md
> +In the ROSbot's shell execute (in the `/home/husarion/rosbot-docker/demo directory`)
```suggestion
In the ROSbot's shell execute (in the `/home/husarion/rosbot-docker/demo` directory)
```

2023-05-25 10:09 UTC, macstepien commented on demo/README.md
> +Visualization for ROSbot 2R, ROSbot 2 PRO and ROSbot 2.0 sensors.
Update description

2023-05-25 10:09 UTC, macstepien commented on demo/compose.simulation.yaml
> +    image: husarion/rosbot-gazebo:humble-add-simulation-and-demo
it will be necessary to change it, i think `husarion/rosbot-gazebo:humble` will be the best

2023-05-25 10:09 UTC, macstepien commented on demo/compose.yaml
> +    image: husarion/rosbot:humble-add-simulation-and-demo
same here

2023-05-25 11:43 UTC, macstepien commented
I also checked changes on ROSbot and everything is alright.

2023-05-25 13:56 UTC, macstepien approved these changes

2023-05-25 13:59 UTC, merged